# Generated by Django 3.1.5 on 2021-10-24 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Note', max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('relevant', models.BooleanField(default=False)),
                ('nexttime', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(default='rgb(224, 224, 224)', max_length=30)),
                ('RevisionDate', models.CharField(blank=True, max_length=32, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserNote', to=settings.AUTH_USER_MODEL)),
                ('inside', models.ManyToManyField(blank=True, to='WritingNotes.Note')),
            ],
        ),
    ]
