# Generated by Django 3.1.5 on 2021-05-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Note', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
