# Generated by Django 3.1.5 on 2021-05-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0002_auto_20210517_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Notes',
            field=models.ManyToManyField(blank=True, to='WritingNotes.Note'),
        ),
    ]
