# Generated by Django 3.1.5 on 2021-05-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0003_auto_20210517_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='nexttime',
        ),
        migrations.AlterField(
            model_name='note',
            name='relevant',
            field=models.BooleanField(default=False),
        ),
    ]
