# Generated by Django 3.1.5 on 2021-10-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Tag',
            field=models.ManyToManyField(blank=True, to='WritingNotes.Tag'),
        ),
    ]
