# Generated by Django 3.1.5 on 2021-05-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0004_auto_20210518_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='inside',
            field=models.ManyToManyField(blank=True, to='WritingNotes.Note'),
        ),
    ]
