# Generated by Django 3.1.5 on 2021-05-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0005_auto_20210518_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lastmodified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
