# Generated by Django 3.1.5 on 2021-05-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0006_auto_20210518_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(),
        ),
    ]
