# Generated by Django 3.1.5 on 2021-05-29 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0008_note_nexttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Notes',
        ),
        migrations.AddField(
            model_name='note',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Userfolder', to=settings.AUTH_USER_MODEL)),
                ('notesinside', models.ManyToManyField(blank=True, to='WritingNotes.Note')),
            ],
        ),
    ]
