# Generated by Django 3.1.5 on 2021-05-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0009_auto_20210528_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='rgb(224, 224, 224)', max_length=30),
        ),
    ]
