# Generated by Django 3.1.5 on 2021-05-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0010_note_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='note',
            old_name='shared',
            new_name='public',
        ),
        migrations.AddField(
            model_name='note',
            name='Tag',
            field=models.ManyToManyField(blank=True, to='WritingNotes.Tag'),
        ),
    ]
