# Generated by Django 3.1.5 on 2021-06-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0011_auto_20210531_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='rgb(224, 224, 224)', max_length=30),
        ),
    ]
