# Generated by Django 3.1.5 on 2021-06-04 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0012_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
