# Generated by Django 3.1.5 on 2021-06-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0014_auto_20210605_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='nexttime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
