# Generated by Django 3.1.5 on 2021-06-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0015_auto_20210606_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='User',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='rgb(224, 224, 224)', max_length=30, null=True),
        ),
    ]
