# Generated by Django 3.1.5 on 2021-06-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0016_auto_20210608_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TagsfromUser', to='WritingNotes.user'),
        ),
    ]
