# Generated by Django 3.1.5 on 2021-06-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WritingNotes', '0018_note_revisiondate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
